project_name: remote-work-processor
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/remote-work-processor/main.go
    binary: remote-work-processor
    ldflags: -s -w -X main.Version={{.Version}} -X main.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
dockers:
- dockerfile: Dockerfile
  image_templates:
    - "ghcr.io/sap/{{ .ProjectName }}:{{ .Version }}"
    - "ghcr.io/sap/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
  use: buildx
  goos: linux
  goarch: amd64
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.created={{ .Date }}
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }}
  - --label=org.opencontainers.image.source=https://github.com/sap/{{ .ProjectName }}
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  use: git
release:
  footer: |
    ## Docker Images

    - `docker pull ghcr.io/sap/{{.ProjectName}}:{{ .Version }}`
