name: Custom Image

on:
  workflow_dispatch:
    inputs: {}

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io/sap
  IMAGE_NAME: dev-${{ github.event.repository.name }}

jobs:
  custom-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          VERSION: sha-${{ steps.vars.outputs.sha_short }}
        run: |
          env
          make IMAGE_NAME="$IMAGE_NAME" VERSION="$VERSION" image

      - name: Push image
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ steps.vars.outputs.sha_short }}
        run: docker push "$IMAGE"
